# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: combined34rel_1.proto
# plugin: python-betterproto
import builtins
from dataclasses import dataclass
from typing import Dict, List

import betterproto
